on: [pull_request]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    name: A job to publish a package to github package
    steps:
      - id: foo
        uses: Naya-01/composite-actions@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
